// <auto-generated />
namespace RoomBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class start : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(start));
        
        string IMigrationMetadata.Id
        {
            get { return "202510091746503_start"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
